칭찬 메세지 생성 (물 주기) API 설계
YAPP-Github/20th-Web-Team-1-BE pull request #13
Opened 2022-06-08 14:03 UTC by suubinkim

## 이슈
- #12 

## 작업 내용
- 칭찬 메세지 생성 API
- Controller Test Case 작성

## 기타 사항
- jwt 토큰 디코딩 하는 부분 추가 필요
- message에서 sender -> senderId로 변경

## 체크리스트

2022-06-08 14:05 UTC, suubinkim commented
완성은 아니고 1차로 올림니다..!  피드백 부탁드려요 제가 이해한 대로 코드 작성했는데 비슷하게 생각 하셨는지 모르겠네요
이해 안 가는 부분 있으시면 물어보세요!!

2022-06-11 06:00 UTC, kang-jisu requested changes
수빈님 넘 수고하셨어요 제가 더 빨리확인했어야했는데!ㅠㅠ

일단은 몇가지 남겨봤구요 !! 
물주기 생성후에 응답으로 돌려줄 값만 프론트엔드분들이랑 얘기해서 정하면 좋을거같아요! (따로 데이터 안돌려줘도되는지 / id같은정도만 돌려줄지 / 생성된 데이터 전부 다시 돌려줄지?)

테스트코드 부분이랑 user 연동은 저도 얼른 작업해서 같이 바꿔봐요 ..!!

2022-06-11 06:00 UTC, kang-jisu commented on src/main/java/com/yapp/betree/controller/MessageController.java
> +        }
이부분은 어떤의미로 하신건지 느낌은와서 로그인부분 구현되면 같이 변경해보면 좋을거같아요!
로그인하지 않은 유저일경우 처리, 토큰 유효성 처리 부분은 얼른 저도 적용해보고 다시 얘기드릴게요!!

2022-06-11 06:00 UTC, kang-jisu commented on src/main/java/com/yapp/betree/controller/MessageController.java
> +        return ResponseEntity.noContent().build();
보통 성공에대한 HTTP 응답코드는
```
200 : 일반적인 성공
201 : created (잘 생성되었음)
204 : no content (삭제되어서 돌려줄 값이 없는경우?)
```
구분을 한다면 이런정도가 좋을 것 같아서 noContent보다는 created가 어울려보이는데 혹시 어떻게 생각하실까요!!

아니면 프론트엔드분들이랑 얘기해서 물주기 생성시에 생성된 메시지 id라던가,, 뭔가 필요한 응답값 있는지 물어보고 바꿔도좋을거같아요 

추가로 만약에 noContent로 쓰게되는 경우에는 메서드 반환값 `ResponseEntity<Object>`말고 `ResponseEntity<Void>`로 반환할 값이 없다고 명시해주는것도 좋을거같아요!!

2022-06-11 06:00 UTC, kang-jisu commented on src/main/java/com/yapp/betree/domain/Message.java
> +    }
좋은거같아요오 👍

2022-06-11 06:00 UTC, kang-jisu commented on src/main/java/com/yapp/betree/dto/request/MessageRequestDto.java
> +    private String folderName;
아마 프론트엔드쪽에서 folderId를 가지고 있을거라 이름 변경될 수 도 있는 `folderName` 보단 고유 id 값으로 받는건 어떠신지요!!

2022-06-11 06:00 UTC, kang-jisu commented on src/main/java/com/yapp/betree/service/MessageService.java
> +        );
👍
저희 나중에는 전역예외처리 만들어서 다른 커스텀예외나 메시지 포함해줘야겠어요!!

2022-06-11 06:00 UTC, kang-jisu commented on src/main/java/com/yapp/betree/service/MessageService.java
> +                .build();
message-folder 연관관계 설정이 이렇게만 넣어도 잘 들어가지는지 테스트 한번 해보면 좋을거같아요!!

2022-06-11 06:00 UTC, kang-jisu commented on src/main/java/com/yapp/betree/service/MessageService.java
> +@Transactional
Service 클래스단에 `@Transactional` 걸게될 때는 `@Transactional(readOnly=false)` 옵션이랑 같이 걸어줘야 할거예요!
클래스단에 걸어두고 일반적인 조회메서드에는 따로 추가하지않고 
나머지 수정/생성/삭제 관련 로직있는 메서드에만 `@Transactional` 추가하는방식으로요!

https://www.inflearn.com/questions/118698

2022-06-11 06:00 UTC, kang-jisu commented on src/test/java/com/yapp/betree/controller/MessageControllerTest.java
> +    }
이렇게하게되면 매번 테스트코드돌릴때마다 새로운테스트데이터 디비에 계속 쌓이게될까요!?
임시로 테스트데이터 만드시려고 이렇게하신거같긴한데 .. 아니면 `@AfterEach` 같은데서 다시 삭제해주는건 어떨까요오 .. 
저도 테스트 데이터를 어떻게만들어서 활용해야할지는 좀 더 고민해볼게요!!

2022-06-11 06:02 UTC, suubinkim commented on src/main/java/com/yapp/betree/dto/request/MessageRequestDto.java
> +    private String folderName;
엇 그게 맞는것 같네요 수정하겠습니다~!

2022-06-11 06:03 UTC, suubinkim commented on src/main/java/com/yapp/betree/service/MessageService.java
> +        );
네넹.>!! 저도 그 생각해서 일단 저렇게만 했습니다

2022-06-11 06:05 UTC, suubinkim commented on src/test/java/com/yapp/betree/controller/MessageControllerTest.java
> +    }
네네 계속 쌓여요! @AfterAll 만 해보다가 다 삭제되서 일단 없앴는데 @AfterEach 것도 적용해보고 테스트 해볼게용

2022-06-11 06:05 UTC, suubinkim commented on src/main/java/com/yapp/betree/service/MessageService.java
> +                .build();
제가 테스트해봤을때는 잘 됐습니다..!!

2022-06-15 15:24 UTC, suubinkim commented on src/main/java/com/yapp/betree/dto/response/MessageBoxResponseDto.java
> +}
dto를 좀 나눠서 클래스명이 헷갈리게 되었는데 요건 메세지함목록 조회할때 리턴하는 dto 입니당..
기존 messageResponseDto랑 합칠까하다가.. 나눴는데 나중에 봐서 합치는게 나으면 합쳐요
그리고 지금 생각났는데 받은 날짜도 넣어야겠네요 ㅎ ㅠㅠ

2022-06-15 16:11 UTC, kang-jisu requested changes
수고하셨습니다아.. 👍
다른 부분들은 다 괜찮아보이고 이전에 물주기 리턴값 아직 `noContent()`로 남아있는거랑 (테스트코드는 Created인데 안맞고있음) @Transactioanl(readOnly=true) 설정이 아직 안바뀌어있어서 그거만 바꿔주시고 머지하면 될거같아요!

2022-06-15 16:11 UTC, kang-jisu commented on src/main/java/com/yapp/betree/dto/response/MessageBoxResponseDto.java
> +}
넵!! 나중에 합치는거랑 이름 구분만 저희끼리 정해보져!!

2022-06-15 16:11 UTC, kang-jisu commented on src/main/java/com/yapp/betree/service/MessageService.java
> +        PageRequest pageRequest = PageRequest.of(page, 7, Sort.by(Sort.Direction.DESC, "createdDate"));
혹시 size를 7로 정한 이유가 따로 있으실까요?? 제가 메시지함 무한스크롤 부분을 살짝 건너들어버려서 ..@_@ 
그냥 임의로 정하신거면 상관없습니당 ! 
```java
private static final int PAGE_SIZE = 7;
```
대신 이런식으로 상수처리해도 좋을거같아요!

2022-06-16 13:07 UTC, suubinkim commented on src/main/java/com/yapp/betree/service/MessageService.java
> +        PageRequest pageRequest = PageRequest.of(page, 7, Sort.by(Sort.Direction.DESC, "createdDate"));
네네 스크롤부분은 저도 따로 얘기한게 없는 것 같아서 피그마 보고 보이는 게 7개라 임의로 했어용 ㅎㅎ..상수처리 할게요~~

2022-06-21 11:54 UTC, kang-jisu approved these changes

2022-06-21 16:51 UTC, merged