나무, 나무숲 API
YAPP-Github/20th-Web-Team-1-BE pull request #18
Opened 2022-06-14 17:32 UTC by suubinkim

## 이슈
- #17 

## 작업 내용
- 유저 나무숲 조회 (페이징)
- 유저 상세 나무 조회 (이전,다음 나무)
- 나무 추가
- 나무 편집
- API 테스트 케이스

## 기타 사항
- controller에서 토큰 처리 과정 필요
- 예외처리, 응답 값 형식 설정 필요
- 상세 나무 조회시 이전, 다음 페이지 없을 때 처리 고민 (일단 try catch 문으로 0L 값 설정)
- 이전, 다음 treeId를 JPA로 각각 가져왔는데 더 좋은 방법이 있을까..?! (구글링으론 쿼리문 밖에 못 찾음)
--> prev,nextId에 treeId 넣는게 맞나요? 잘 이해한건지..
- 응답 값 DTO 만들었다가 정하고 수정하려고 삭제했습니다..

## 체크리스트

2022-06-15 16:51 UTC, kang-jisu requested changes
구현 잘해주셨네요오ㅠㅠ !! 😆
prevId, nextId도 treeId 넣는거 맞습니당!! 예외처리할때 반환값은(지금0L넣은거) 담에 한번 정해보면 될거같아요
응답 DTO나 좀 자잘한 것들은 나중에 정하거나 한번에 리팩토링하는게 좋을 것 같아서 볼때 궁금한 부분들 위주로만 리뷰남깁니당!! 수고많으셨어요 🙇‍♀️

2022-06-15 16:51 UTC, kang-jisu commented on src/main/java/com/yapp/betree/service/FolderService.java
> +        return folder;
이건 개인취향이긴 한데 저는 Controller<->Service로 전달되는 모든 값을 다 DTO 처리하는 방식으로 구현해봤었거든요..! 컨트롤러단에 domain 엔티티 그대로 노출되는거 방지하는게 좋을 것 같았어서요!
지금 당장은 CreateTree의 결과로 Tree를 리턴했을 때 id만 쓰는거같은데, 아예 리턴값을 id 로 바꾸거나 반환용 FolderDto를 만드시는거에대해서 어떻게 생각하실까요..! 단순 그냥 의견입니다!! 

-> 커밋 순서대로 보고있어서 뒤에 커밋에서는 void로 바꿔있군여!! 나중에 다른 반환값 설정할 때만 참고부탁드려용

2022-06-15 16:51 UTC, kang-jisu commented on src/main/java/com/yapp/betree/service/FolderService.java
> +    }
단순 질문인데 지금 저희 구현상으로 보면 프론트쪽에서 update할 때 변경되지 않는 부분은 기존값 그대로 채워서 보내주는거 맞나요 ?-?

2022-06-15 16:51 UTC, kang-jisu commented on src/main/java/com/yapp/betree/controller/ForestController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
뭔가 저도 기준이 잡혀있지는 않은데 수정에 대해서 created로 응답하는게 살짝 어색하네요..! 진짜 새로 생성될 때만 created로 쓰고 나머지 요청들에 대해서는 그냥 200 OK 쓰는건 어떨까요!(삭제는 204 or 200 정해서)

2022-06-15 16:51 UTC, kang-jisu commented on src/main/java/com/yapp/betree/repository/MessageRepository.java
> +    List<Message> findTop8ByFolderIdAndOpening(Long treeId, boolean opening);
👍

2022-06-15 16:51 UTC, kang-jisu commented on src/main/java/com/yapp/betree/service/FolderService.java
>          }
anonymous==true이면 sender.getNickname에 "익명" 같이 반환하도록 변경해주면 좋을거같아요!

2022-06-15 16:51 UTC, kang-jisu commented on src/main/java/com/yapp/betree/repository/FolderRepository.java
> +    Page<Folder> findByUserId(Long userId, Pageable pageable);
물주기쪽 페이징에서는 `Slice`사용하신 거 같은데 혹시 Page랑 Slice 다르게 쓴 이유가 있으신가여??

2022-06-16 13:08 UTC, suubinkim commented on src/main/java/com/yapp/betree/controller/ForestController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
아 컨트롤러부분은 아직 아예 신경 안 쓰고 했어요..! 나중에 정하면 바꿀려구 ㅎㅎ..네네 생성될때만 201이 맞는 것같아요 수정할게요 !!

2022-06-16 13:11 UTC, suubinkim commented on src/main/java/com/yapp/betree/repository/FolderRepository.java
> +    Page<Folder> findByUserId(Long userId, Pageable pageable);
제가 페이징을 이번에 첨해봐서 검색해봤는데 page랑 slice가 똑같은데 slice가 토탈수  안 세고 다음 페이지 존재여부만 확인해서 쿼리 덜 나간다고 하더라구요 그래서 큰 차이는 없는데 데이터많아지거나 하면 무한스크롤에서는 토탈수 필요없으니까 slice로 해도 괜찮다는 글을 봐서 다르게 썼습니다.. 근데 통일하는게 나을까요..?

2022-06-16 13:14 UTC, suubinkim commented on src/main/java/com/yapp/betree/service/FolderService.java
>          }
아아 그걸 생각 못했네요 감사합니다 !!

2022-06-16 14:15 UTC, suubinkim commented on src/main/java/com/yapp/betree/service/FolderService.java
> +    }
네 !

2022-06-16 14:39 UTC, kang-jisu commented on src/main/java/com/yapp/betree/repository/FolderRepository.java
> +    Page<Folder> findByUserId(Long userId, Pageable pageable);
아니요!!! 이유있을때 다르게 쓰는게 맞을거같은데 저도 어떨때 어떤거썼는지 잠깐 헷갈려서요!! 좋은거같아용 만약에 이 코드도 Slice로 쓸수있으면 쓰면어떨까해요!!

2022-06-16 15:27 UTC, suubinkim commented on src/main/java/com/yapp/betree/repository/FolderRepository.java
> +    Page<Folder> findByUserId(Long userId, Pageable pageable);
아아.. 이것도 그냥 이전 다음버튼이라 slice로 해도 되겠네요..! 왜 토탈이 있어야한다고 생각했지.. 좋습니다..!

2022-06-21 11:54 UTC, kang-jisu approved these changes
☺️👍

2022-06-21 16:51 UTC, merged