refactor: 물주기, 메세지함 API 작업
YAPP-Github/20th-Web-Team-1-BE pull request #34
Opened 2022-06-27 15:32 UTC by suubinkim

## 이슈
- #21 
- #24 

## 작업 내용
- [x] 물주기, 메세지 목록 조회, 열매 맺기 ApiRespinse 수정
- [x] 물주기 - folderId가 null일때 수신자 디폴트 폴더로 처리
- [x] MessageController, Service 테스트 케이스 추가 및 수정
- [ ] 메세지 삭제
- [x] 메세지 폴더 이동
- [x] 메세지 즐겨찾기 설정
- [x] 즐겨찾기한 메세지 목록 조회
++
- [ ] 메세지 dto에 작성일자/시간 추가
- [x] 메세지 읽음 여부 변경 API

## 기타 사항
- controller에서 바로 pageable 받기
- 예외처리로 optional 사용
- stream 사용
- 메세지 삭제 - 1차로 물리 삭제 처리 (나중에 삭제여부 필드 추가 필요)
- 물주기 - 비로그인시 처리 필요

## 체크리스트

2022-06-27 17:12 UTC, kang-jisu requested changes
기능 테스트, Optional Stream 적용 다 넘 잘해주셨네요!! 😆👍
몇가지 코멘트 남길테니 확인부탁드릴게요!

그리고 토요일에 그냥 머지해버리느라 못한 리뷰 이전 PR에 마저 남겨놨는데 그것도 확인해주시면 좋을 것 같아요 !! 
링크 : #27 
❤️

2022-06-27 17:12 UTC, kang-jisu commented on src/test/java/com/yapp/betree/controller/MessageControllerTest.java
> +                .andExpect(jsonPath("$.message").value("Invalid input value"));
`andExpect(jsonPath("$.errors[0].message").value(""))`
저도 몇개는 그냥 C001 에러로 확인했는데 앞으로 validation 예외처리 테스트할 때 저희 jsonPath값 이렇게 지정해서 확인하면 혹시 예외처리 메시지 달라졌을 때 관련 테스트코드 발견하기 좋을 것 같아요!

2022-06-27 17:12 UTC, kang-jisu commented on src/test/java/com/yapp/betree/controller/MessageControllerTest.java
> +        given(messageService.getMessageList(anyLong(), any(), eq(19L))).willThrow(new BetreeException(ErrorCode.TREE_NOT_FOUND));
오 이건 그냥 질문인데 mock 처리할 때 eq(19L)처럼 쓰면 param으로 전달한 treeId 19L에 맞게 되는건가요!!
저 가끔 예외처리할 때 그냥 19L로 적었더니 안되서 treeId부분에도 anyLong()써서 대충 해결한 것 같거든요 ㅠ 
참고하겠습니당 👍

2022-06-27 17:12 UTC, kang-jisu commented on src/test/java/com/yapp/betree/service/MessageServiceTest.java
> +    private final Pageable pageable = Mockito.mock(Pageable.class);
오호 Pagable mock 처리 알아갑니다 👍

2022-06-27 17:12 UTC, kang-jisu commented on src/main/java/com/yapp/betree/controller/MessageController.java
> +                                                                 @PageableDefault(sort = "createdDate", direction = Sort.Direction.DESC) Pageable pageable,
❤️

2022-06-27 17:12 UTC, kang-jisu commented on src/main/java/com/yapp/betree/controller/MessageController.java
> +        log.info("[messageIdList] : {}", messageIds + ", [loginUser Id] : " + loginUser.getId());
```java
 log.info("[messageIdList] : {}, [loginUser Id] : {}", messageIds, loginUser.getId());
```
이렇게 처음 string에 {}로 구분해서 한번에 넣고 뒤에 인자 추가할 수 있어요!

2022-06-27 17:12 UTC, kang-jisu commented on src/main/java/com/yapp/betree/dto/response/MessagePageResponseDto.java
> +                .hasNext(hasNext)
질문이 있는데 페이징 처리 들어갈 때 마다 hasNext 필드 추가하시던데 혹시 이게 어떤의미로 쓰이는건가요!!?? 
(이상하거나 빼자는건 아니고 아니고 따로 검색하거나 코드보고 이해하기 귀찮아서 쓸모가있어서 추가하신거겠지~~하고 자꾸 넘겨버려서 질문드려요 ㅋㅋㅋ 🙇‍♀️ )
hasNext는 있는데 hasPrev는 안하시는 이유라던가 ,, Slice 쓸 때 제공되는 기능중에 하나인가요 ??

2022-06-27 17:12 UTC, kang-jisu commented on src/main/java/com/yapp/betree/service/MessageService.java
> +        });
👍

그냥 리뷰니까 쪼금 더 빡빡하게 남기자면 
근처에서 사용하는 Id가 userId, messagesId로 구분이 필요하니까 forEach에서 사용하는 'id'가 messageId라고 명시해주는게 나중에 보기에 안헷갈릴것 같아요!

2022-06-27 17:58 UTC, kang-jisu commented on src/test/java/com/yapp/betree/controller/MessageControllerTest.java
> +                        .param("isLogin", String.valueOf(true))
`isLogin` 쓰이지 않는 param이 아직 남아있는 것 같네요! 지워야할 것 같아요

2022-06-28 13:06 UTC, suubinkim commented on src/test/java/com/yapp/betree/controller/MessageControllerTest.java
> +        given(messageService.getMessageList(anyLong(), any(), eq(19L))).willThrow(new BetreeException(ErrorCode.TREE_NOT_FOUND));
저도 안돼서 검색해봤더니 Mockito 쓸때 여러 인자 중에 하나라도 any()같은 임의값 사용하면 나머지도 그런 처리를 해줘야되서 특정값 쓰려면  eq쓰는거라고 하더라고용.. Argument Matcher 검색하면 나와요 !!

2022-06-28 13:17 UTC, suubinkim commented on src/main/java/com/yapp/betree/dto/response/MessagePageResponseDto.java
> +                .hasNext(hasNext)
hasNex가 다음 데이터가 있는지 여부인데 제가 찾아본거랑 이해한거 같이 말하자면,, 무한 스크롤은 더보기같은 거니까  다음 페이지가 있나만 확인 하면 될 것 같아서 hasNext만 추가한거예요 있으면 더 보여주고 없다면 그만 이런 식으로.. ? 근데 프론트쪽에서 어떨지 잘 모르겠어요 ㅋㅋ

2022-06-28 16:32 UTC, kang-jisu commented on src/main/java/com/yapp/betree/dto/response/MessagePageResponseDto.java
> +                .hasNext(hasNext)
아!무한스크롤경우를 생각하면 hasNext여부가 필요하겠네요!! 좋습니다아

2022-06-28 16:53 UTC, kang-jisu approved these changes
머지해도 좋을 것 같아요 ☺️

2022-06-28 16:53 UTC, kang-jisu commented on src/main/java/com/yapp/betree/domain/Message.java
> +        this.alreadyRead = true; //false 될 수 없음
👍

2022-06-29 13:17 UTC, merged