[feat] 유저 조회 및 닉네임 변경 API
YAPP-Github/20th-Web-Team-1-BE pull request #53
Opened 2022-07-05 15:21 UTC by suubinkim

## 이슈
- #40 

## 작업 내용
- 유저 정보 조회
- 유저 닉네임 변경

## 기타 사항
- controller에서 닉네임 변경에서 닉네임 하나만 받아서 requetParam 하고 거기에 바로 valid하려했는데 안 먹히더라구요 ㅠ 그래서 class에 validated 추가했는데 나중에 수정 가능하면 하겠습니다
- 마이페이지에 url복사하기가 있어서 정보 조회시에 같이 줘야하나 하고 dto에 포함했는데 프론트쪽에서 복사를 어떤 식으로 하는지 몰라서 이게 맞나 좀 찜찜하네요
- 닉네임 변경 api도 실제로 바뀌는지 테스트해보고 싶어서 AcceptanceTest에 추가하고 Claims 도 추가했는데 괜찮은가여..

## 체크리스트
- [ ] example

2022-07-07 15:11 UTC, kang-jisu requested changes
테스트도 꼼꼼하게 넘 잘해주신거같습니다!! 💯💯
몇가지 남긴부분 한번 확인부탁드릴게요!!

> controller에서 닉네임 변경에서 닉네임 하나만 받아서 requetParam 하고 거기에 바로 valid하려했는데 안 먹히더라구요 ㅠ 그래서 class에 validated 추가했는데 나중에 수정 가능하면 하겠습니다  

원래 `@Valid`가 클래스단위로만 동작하는거라 String, Long에는 안먹어서 지금처럼 구현하신게 맞는방법일거예요! 

> 마이페이지에 url복사하기가 있어서 정보 조회시에 같이 줘야하나 하고 dto에 포함했는데 프론트쪽에서 복사를 어떤 식으로 하는지 몰라서 이게 맞나 좀 찜찜하네요   

DTO에 포함해서 보내는거 전 좋아보입니다!! 

> 닉네임 변경 api도 실제로 바뀌는지 테스트해보고 싶어서 AcceptanceTest에 추가하고 Claims 도 추가했는데 괜찮은가여..  
혹시 테스트 성공하시나요? ㅠㅠ 
```java
 @Test
    @DisplayName("유저 닉네임 변경 테스트")
    void updateUserNickname() throws Exception {
        User user = UserTest.TEST_USER;
        userRepository.save(user);

        String token = JwtTokenTest.JWT_TOKEN_TEST;
        given(jwtTokenProvider.parseToken(token)).willReturn(claims(user.getId()));
```
jwtTokenProvider를 mock처리하게되는데 AcceptanceTest에 다른 테스트들은 `@Autowired`로 받아온 jwtTokenProvider를 써야 제대로 동작할거라 제생각에는 닉네임변경테스트용+jwtTokenProvider를 `@MockBean`으로 설정하는 테스트클래스 따로 분리하는게 좋을 것 같아요! MessageAcceptanceTest 처럼요 !!

2022-07-07 15:11 UTC, kang-jisu commented on src/main/java/com/yapp/betree/controller/UserController.java
> +    @GetMapping("/api/user")
기본적으로 다른 api들이 복수형을 쓰고있어서 `/api/users/info` 이런식이여도 좋을 것 같아요!
그냥 `/api/users`만 하자니 전체리스트를 가져오는거 같기도 해서 info 같은거도 추가하는방식으로 ..!! 
어떠실까요!

2022-07-07 15:11 UTC, kang-jisu commented on src/main/java/com/yapp/betree/controller/UserController.java
> +    @PatchMapping("/api/user")
위에 남긴거랑 비슷하게 이것도 `/api/users/nickname`정도로 좀 더 상세하게 url을 변경해도 좋을 것 같고, 

저는 개인적으로 HTTP Method를 GET POST (PUT, DELETE)정도만 사용하는것도 나쁘지는 않아보여요! 프론트백엔드끼리 약속만 되어있다면 엄청 세세하게 규칙을 지키는 것 보다는 덜 헷갈리고 통일성있게 하는게 더 낫다는 의견입니다!! 
닉네임만 변경한다고 Patch로 바꾸기엔 다른 변경 메서드들은 다 PUT으로 되어있기도 해서요 !(메시지 boolean값 변경에 대한 것들도..!)

+)
아니면 기존 put이었던것들도 의미에 맞게 바꿀만한거있으면 patch로 바꾸고 쓰는게 좋을거같아요!

그냥 제 개인적인 의견이니깐 한번 생각해봐주세욥 !

2022-07-07 15:11 UTC, kang-jisu commented on src/main/java/com/yapp/betree/dto/response/UserResponseDto.java
> +    public static UserResponseDto of(User user) {
☺️👍

2022-07-07 15:11 UTC, kang-jisu commented on src/test/java/com/yapp/betree/controller/UserControllerTest.java
> +    @DisplayName("유저 닉네임 변경 - 공백일때 예외처리")
👍

2022-07-07 15:11 UTC, kang-jisu commented on src/test/java/com/yapp/betree/controller/UserControllerTest.java
> +    @DisplayName("유저 닉네임 변경 - 글자수 20자 초과시 예외처리")
👍

2022-07-09 12:44 UTC, suubinkim commented on src/main/java/com/yapp/betree/controller/UserController.java
> +    @PatchMapping("/api/user")
저도 하면서 이것만 patch라 맞나 싶긴했는데 통일하는게 맞는것 같아요 그럼 기존것들은 나두고 이걸 변경할게요..!

2022-07-09 13:24 UTC, merged