[feat] 서랍메뉴 - 나무 공개 설정
YAPP-Github/20th-Web-Team-1-BE pull request #72
Opened 2022-07-12 16:19 UTC by suubinkim

## 이슈
- #45 
## 작업 내용
- 나무 공개 설정 api
- 나무 숲 조회 api 수정 - 조회 유저에 따라 전체 또는 공개 나무 조회

## 기타 사항
- folderAcceptanceTest에 테스트 작성하려고 하는데 이거 넣으면 여기저기서 갑자기 에러나고 이거 빼면 전체 성공하더라구요.. 하나만 돌리면 성공하구요.. 그래서 일단 뺏습니다... 

## 체크리스트
- [ ] example

2022-07-14 00:27 UTC, kang-jisu requested changes
수빈님 수고하셨습니다아~ 

지금 tokenInterceptor 부분에서 조건문분기가 잘 안되고있을거같아서 mock으로 컨트롤러 테스트하는거말고 folderAcceptanceTest 를 하긴 해야할거같아요! 하나만 돌렸을땐 그래도 성공하는거면 일단 테스트코드 다시 작성해서 `@Disabled` 처리해서 올려주실수있을까요?? 저도가끔 그런테스트들 있어서 ㅠ 
몇가지 보고 코멘트 남겨둘게요~!! 감사합니당

2022-07-14 00:27 UTC, kang-jisu commented on src/main/java/com/yapp/betree/controller/ForestController.java
> +                                         @RequestParam Long treeId) {
삭제랑 편집이랑 컨벤션을 맞추려면 treeId가 pathvariable인게 좋지 않을까요?

2022-07-14 00:27 UTC, kang-jisu commented on src/main/java/com/yapp/betree/service/FolderService.java
> +        folder.updateOpening();
기획상 기본폴더는 나무 비공개처리 하는거 추가해야되려나요 저희 ??

2022-07-14 00:27 UTC, kang-jisu commented on src/test/java/com/yapp/betree/service/FolderServiceTest.java
> +    @DisplayName("유저 나무 공개 - 공개 설정하려는 나무가 존재하지 않으면 에외가 발생한다.")
```java
    /**
     * 나무(폴더) 처리시에 userId, treeId 검증 및 tree 주인과 user 일치여부 파악
     *
     * @param userId
     * @param treeId
     * @return Folder
     */
    private Folder validateAndGetFolder(Long userId, Long treeId) {
```

FolderService에 이 로직 쓰는 메서드들은 위에 유저나무 - 라고 해서 한번에 테스트 하고있어서 나무존재에러, 주인일치여부에러 테스트는 삭제해도될거같아요!

2022-07-14 00:27 UTC, kang-jisu commented on src/main/java/com/yapp/betree/interceptor/TokenInterceptor.java
> +                request.getRequestURI().equals("/api/forest") && request.getMethod().equals(String.valueOf(HttpMethod.GET))) {
나무숲 상세조회랑 나무숲 조회가 둘다 /api/forest/로 시작하고 get 메소드라서 지금 상태로는 나무상세조회 조건문에서 바로 true가 될거같은데 맞나요..? 나무숲조회일때 뒤에 treeId 요청하는거로 구분하거나 url을 좀 변경해야될거같아욥

2022-07-14 00:27 UTC, kang-jisu commented on src/main/java/com/yapp/betree/service/FolderService.java
> +        return folderRepository.findAllByUserIdAndOpening(userId, true)
이부분은 로직상 문제는 없긴 한데 나무숲에 나무 자체가 많지 않아서 그냥 `findAllByUserId`로만 조회한다음에 `stream.filter`로 opening 걸러도 되지 않을까요?! 또 나무숲에서 보여지는 조건이 달라질때마다 레파지토리에 메서드를 계속 추가하게 되는것보단 백엔드단에서는 적당히 전체를 가져와서 코드로 필터링해도 될거같아요!!

2022-07-14 16:23 UTC, suubinkim commented on src/main/java/com/yapp/betree/interceptor/TokenInterceptor.java
> +                request.getRequestURI().equals("/api/forest") && request.getMethod().equals(String.valueOf(HttpMethod.GET))) {
아 제가 테스트 하면서 리턴 값 맞게 나오게 하려고 이렇게 저렇게 해봤는데 상세조회는 true나와야 하는게 맞는거 아닌가요..!? 그래서 상세랑 나무 숲 조회 조건문 안 겹치게 하려고 상세조회 조건문에 원래 /api/forest 였는데 마지막에 / 붙여서 나무 숲 조회랑 구별하고 나무숲 조회 조건문은 startsWith 말고 equals로 했어용 

제가 이해 잘 못 한 부분 있을까요?!

2022-07-14 16:23 UTC, suubinkim commented on src/main/java/com/yapp/betree/service/FolderService.java
> +        return folderRepository.findAllByUserIdAndOpening(userId, true)
좋습니다!!

2022-07-14 16:37 UTC, suubinkim commented on src/main/java/com/yapp/betree/service/FolderService.java
> +        folder.updateOpening();
그 boolean 값 초기에 설정 안 하면 false 로 되는거 아닌가용?! ?

2022-07-14 16:38 UTC, suubinkim commented on src/main/java/com/yapp/betree/controller/ForestController.java
> +                                         @RequestParam Long treeId) {
저는 메세지 컨트롤러에서 boolean 값 바꾸는건 다 RequestParam으로 해서 여기도 맞춘거였어요! 움 pathvariable도 저는 상관없는데 그럼 추가해서 컨벤션 맞출까용?!

2022-07-15 00:48 UTC, kang-jisu commented on src/main/java/com/yapp/betree/controller/ForestController.java
> +                                         @RequestParam Long treeId) {
아하 불리언값 바꾸는건 그렇게하신거군요 그럼 그대로해도 괜찮을거같아요~~

2022-07-15 00:49 UTC, kang-jisu commented on src/main/java/com/yapp/betree/service/FolderService.java
> +        folder.updateOpening();
아 초기에는 false돼있군용 넹 예외처리필요할거같아요 기본나무 공개로바꾸려는거 막는걸로요!

2022-07-15 00:50 UTC, kang-jisu commented on src/main/java/com/yapp/betree/interceptor/TokenInterceptor.java
> +                request.getRequestURI().equals("/api/forest") && request.getMethod().equals(String.valueOf(HttpMethod.GET))) {
아하 마지막에 / 이거붙이셨군요 제가 덜봤나봐요ㅜㅜ그럼 이대로하시면 될거같습니당!!

2022-07-17 06:50 UTC, kang-jisu commented
테스트도 여러개 있을때 하나 실패하는게 cascade설정이나 뭔가 해결해봐야할거같긴한데 잘 모르겠네요 ㅠ
일단 다른 문제는 없는거같으니 제가 머지하겠습니당!!

2022-07-17 06:50 UTC, kang-jisu approved these changes

2022-07-17 06:50 UTC, merged